name: Node-Editor-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pip
  - pip:
    - -r requirements.txt
  - python=3.9
#  - numpy
#  - scipy
#  - pandas
#  - ase
#  - matplotlib
#  - python-language-server
#  - jupyterlab
#  - jupyterlab-git
#  - jupyterlab-nvdashboard
#  - jupyterlab-lsp
#  - numba
#  - bokeh
#  - captum
#  - cudatoolkit=11.1
#  - datashader
#  - gh
#  - git
#  - holoviews
#  - hvplot
#  - ipywidgets
#  - optuna
#  - panel
#  - pip:
#  - pyarrow
#  - pytorch=1.9
#  - pytorch-lightning
#  - pyviz_comms
#  - scikit-learn
#  - tensorboard
#  - torchaudio
#  - torchmetrics
#  - torchtext
#  - torchvision
#  - wandb
#  - xeus-python
